# Generated by Django 2.1.4 on 2020-05-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_foodtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='typenames',
            new_name='typename',
        ),
    ]
