# Generated by Django 2.1.4 on 2020-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_axfuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_icon',
            field=models.ImageField(upload_to='icons/%Y/%m/%d'),
        ),
    ]
