# Generated by Django 2.1.4 on 2020-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_status',
            field=models.IntegerField(default=1),
        ),
    ]
